const mongoose = require('mongoose');

let Schema = new mongoose.Schema({
    userId: String,
    haus1: Boolean,
    haus2: Boolean,
    haus3: Boolean,
    haus4: Boolean,
    haus5: Boolean,
    haus6: Boolean,
    haus7: Boolean,
    haus8: Boolean,
    haus9: Boolean,
    haus10: Boolean,
    resturant1: Boolean,
    resturant2: Boolean,
    resturant3: Boolean,
    resturant4: Boolean,
    resturant5: Boolean,
    resturant6: Boolean,
    resturant7: Boolean,
    resturant8: Boolean,
    resturant9: Boolean,
    resturant10: Boolean,
    hotel1: Boolean,
    hotel2: Boolean,
    hotel3: Boolean,
    hotel4: Boolean,
    hotel5: Boolean,
    hotel6: Boolean,
    hotel7: Boolean,
    hotel8: Boolean,
    hotel9: Boolean,
    hotel0: Boolean,
    banned: Boolean,
    update: Boolean,
    bugfix: Boolean
})

module.exports = mongoose.model('economy', Schema)